/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class BitCrusherAudioProcessorEditor  : public AudioProcessorEditor,
public Slider::Listener,
public Timer
{
public:
    BitCrusherAudioProcessorEditor (BitCrusherAudioProcessor&);
    ~BitCrusherAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    // Our callback functions we need to implement to get triggered
    // by our timer and slider when updated
    void timerCallback() override;
    void sliderValueChanged (Slider* sliderThatHasChanged) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
 
    // Create a slider object
    Slider gainSlider;
    Slider effectSlider;

    BitCrusherAudioProcessor& processor;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (BitCrusherAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
